# Generated by Django 5.2.15 on 2026-08-04 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('social', '0004_group_invite_code_group_slow_mode_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='social.group'),
        ),
    ]
