# Generated by Django 5.2.15 on 2026-07-27 21:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'awards_track',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwardEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('submitted', 'ثبت\u200cشده'), ('validating', 'صحت\u200cسنجی هلدینگ'), ('judging', 'در حال داوری'), ('scored', 'امتیازدهی شده'), ('finalist', 'منتخب مرحله نهایی')], default='submitted', max_length=12)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('edit_used', models.BooleanField(default=False, help_text='ویرایش یک\u200cبارمصرف مصرف شد')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='awards.awardtrack')),
            ],
            options={
                'db_table': 'awards_entry',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
