# Generated by Django 5.2.15 on 2026-08-03 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('due', models.CharField(blank=True, help_text='سررسید (جلالی نمایشی)', max_length=20)),
                ('status', models.CharField(choices=[('done', 'انجام\u200cشده'), ('in_progress', 'در حال انجام'), ('upcoming', 'پیش\u200cرو'), ('at_risk', 'در خطر')], default='upcoming', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'projects_milestone',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('critical', 'بحرانی')], default='medium', max_length=8)),
                ('probability', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', max_length=6)),
                ('status', models.CharField(choices=[('open', 'باز'), ('mitigating', 'در حال رفع'), ('closed', 'بسته')], default='open', max_length=10)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('mitigation', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'projects_risk',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
