# Generated by Django 5.2.15 on 2026-08-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_milestone_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, help_text='معاونت/دپارتمان مالک پروژه', max_length=120),
        ),
    ]
