# Generated by Django 5.2.15 on 2026-08-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_playbooktemplate_projectexpense_projectmember_and_more'),
        ('tenancy', '0002_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.holding'),
        ),
        migrations.AddField(
            model_name='project',
            name='scope',
            field=models.CharField(choices=[('global', 'سراسری'), ('holding', 'هلدینگ'), ('company', 'شرکت')], default='global', max_length=8),
        ),
    ]
