# Generated by Django 5.2.15 on 2026-08-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, db_index=True, help_text='کد لینک دعوت — با چرخش باطل می\u200cشود', max_length=32),
        ),
        migrations.AddField(
            model_name='group',
            name='slow_mode_seconds',
            field=models.PositiveSmallIntegerField(default=0, help_text='حالت آهسته بین پیام\u200cها'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='last_message_at',
            field=models.DateTimeField(blank=True, help_text='برای حالت آهسته', null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='muted',
            field=models.BooleanField(default=False, help_text='اعلان\u200cهای گروه بی\u200cصدا'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'مالک'), ('admin', 'مدیر'), ('member', 'عضو')], default='member', max_length=8),
        ),
    ]
