# Generated by Django 5.2.15 on 2026-08-04 21:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_group_invite_code_group_slow_mode_seconds_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='topics_enabled',
            field=models.BooleanField(default=False, help_text='حالت تاپیک (فروم) گروه'),
        ),
        migrations.CreateModel(
            name='GroupTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, help_text='ایموجی تاپیک', max_length=8)),
                ('color', models.CharField(default='#1f4f99', max_length=9)),
                ('closed', models.BooleanField(default=False, help_text='بسته — فقط مدیران می\u200cنویسند')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topics', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_topics', to='social.group')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'social_group_topic',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
