# Generated by Django 5.2.15 on 2026-07-27 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('field', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('open', 'فراخوان باز'), ('review', 'بررسی درخواست\u200cها'), ('judging', 'داوری'), ('running', 'در حال اجرا'), ('closed', 'پایان\u200cیافته')], default='open', max_length=8)),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('supervisor', models.CharField(blank=True, max_length=200)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'research_opportunity',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('review', 'در بررسی'), ('accepted', 'پذیرفته'), ('rejected', 'رد شده')], default='review', max_length=8)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='research.researchopportunity')),
            ],
            options={
                'db_table': 'research_application',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
