# Generated by Django 5.2.15 on 2026-08-04 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfpCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('holding', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('publish', 'انتشار فراخوان'), ('docs', 'دریافت مستندات'), ('biz', 'ارزیابی کسب\u200cوکاری'), ('tech', 'ارزیابی فنی'), ('open', 'بازگشایی پاکات'), ('selected', 'فناور برتر انتخاب شد')], default='publish', max_length=10)),
                ('deadline', models.CharField(blank=True, help_text='مهلت (جلالی نمایشی)', max_length=20)),
                ('channels', models.JSONField(blank=True, default=list, help_text='محل\u200cهای انتشار')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'research_rfp_call',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RfpVendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('biz_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tech_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_opened', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, max_length=80)),
                ('winner', models.BooleanField(default=False)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='research.rfpcall')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'research_rfp_vendor',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sabbatical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professor', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, help_text='شرکت صنعتی میزبان', max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('trl_before', models.PositiveSmallIntegerField(default=0)),
                ('trl_after', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contract', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('call', 'فراخوان'), ('select', 'انتخاب استاد'), ('contract', 'قرارداد'), ('running', 'در حال اجرا'), ('final', 'کتابچه و ارائه نهایی'), ('closed', 'خاتمه')], default='call', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'research_sabbatical',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SabbaticalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال به صنعت و داور'), ('needs_fix', 'نیازمند اصلاح'), ('paid', 'تایید و پرداخت شد')], default='pending', max_length=10)),
                ('paid_amount', models.CharField(blank=True, max_length=80)),
                ('sabbatical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='research.sabbatical')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'research_sabbatical_report',
                'ordering': ['no'],
                'abstract': False,
            },
        ),
    ]
