# Generated by Django 5.2.15 on 2026-07-27 21:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('kind', models.CharField(choices=[('mention', 'منشن'), ('like', 'پسند'), ('comment', 'نظر'), ('system', 'سیستمی'), ('task', 'وظیفه')], default='system', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='notificatio_user_id_4fcc58_idx')],
            },
        ),
    ]
