# Generated by Django 5.2.15 on 2026-07-27 20:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200, unique=True)),
                ('logo_color', models.CharField(default='#1f4f99', max_length=9)),
                ('plan', models.CharField(choices=[('basic', 'پایه'), ('pro', 'حرفه\u200cای'), ('enterprise', 'سازمانی')], default='enterprise', max_length=12)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('cross_tenant', models.BooleanField(default=False, help_text='تعامل بین\u200cسازمانی')),
            ],
            options={
                'db_table': 'tenancy_tenant',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#0d9488', max_length=9)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'tenancy_holding',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenancy.holding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'tenancy_company',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
