# Generated by Django 5.2.15 on 2026-08-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_companymembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='short_name',
            field=models.CharField(blank=True, help_text='نام کوتاه در رابط کاربری', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sso_allow_local',
            field=models.BooleanField(default=True, help_text='اجازه\u200cی ورود محلی در کنار SSO'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sso_auto_create',
            field=models.BooleanField(default=True, help_text='ایجاد خودکار حساب برای کاربرِ تاییدشده در منبع هویت'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sso_provider',
            field=models.CharField(choices=[('none', 'بدون SSO'), ('ldap', 'LDAP / Active Directory'), ('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect'), ('otp', 'ورود با موبایل (OTP)')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sso_url',
            field=models.CharField(blank=True, help_text='نشانی سرویس هویت', max_length=300),
        ),
    ]
