# Generated by Django 5.2.15 on 2026-07-27 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_reminder_days', models.PositiveSmallIntegerField(default=7)),
                ('review_escalation_days', models.PositiveSmallIntegerField(default=15)),
                ('dormant_project_days', models.PositiveSmallIntegerField(default=30)),
                ('screening_threshold', models.PositiveSmallIntegerField(default=80)),
                ('jury_threshold', models.PositiveSmallIntegerField(default=50)),
                ('legal_review_days', models.PositiveSmallIntegerField(default=7)),
                ('retention_percent', models.PositiveSmallIntegerField(default=10)),
                ('prepayment_percent', models.PositiveSmallIntegerField(default=25)),
                ('rate_limit_per_minute', models.PositiveSmallIntegerField(default=60)),
                ('edit_window_count', models.PositiveSmallIntegerField(default=1)),
                ('accent', models.CharField(default='brand', max_length=32)),
                ('font_scale', models.CharField(default='normal', max_length=8)),
                ('dark_default', models.BooleanField(default=False)),
                ('enabled_modules', models.JSONField(blank=True, default=list)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_settings', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'console_workflow_settings',
            },
        ),
    ]
