# Generated by Django 5.2.15 on 2026-08-04 12:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('module', models.CharField(blank=True, max_length=120)),
                ('group_by', models.CharField(blank=True, max_length=120)),
                ('schedule', models.CharField(choices=[('none', 'بدون زمان\u200cبندی'), ('weekly', 'هفتگی'), ('monthly', 'ماهانه')], default='none', max_length=8)),
                ('last_run', models.CharField(blank=True, max_length=40)),
                ('format', models.CharField(default='Excel', max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'console_saved_report',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
