# Generated by Django 5.2.15 on 2026-08-04 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_savedreport'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('org', models.CharField(blank=True, max_length=200)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('expires', models.CharField(blank=True, max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'console_guest_account',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('integration_type', models.CharField(choices=[('in_webhook', 'وب\u200cهوک ورودی'), ('out_webhook', 'وب\u200cهوک خروجی'), ('bot', 'بات'), ('slash', 'دستور اسلش')], default='in_webhook', max_length=12)),
                ('channel', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'console_integration',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
