# Generated by Django 5.2.15 on 2026-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_guestaccount_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsettings',
            name='admin_pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='allowed_file_extensions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
