# Generated by Django 5.2.15 on 2026-08-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_workflowsettings_admin_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowsettings',
            name='chunk_size_mb',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='digest_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='feed_page_size',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='image_max_px',
            field=models.PositiveIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='lock_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='login_attempts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='فقط راهبران وارد شوند'),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='notif_batch',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='session_hours',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='upload_max_mb',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='workflowsettings',
            name='user_quota_gb',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
