# Generated by Django 5.2.15 on 2026-08-04 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('photo', 'تصویر'), ('doc', 'سند'), ('audio', 'صوت'), ('video', 'ویدیو'), ('other', 'سایر')], default='other', max_length=8)),
                ('size', models.PositiveIntegerField(default=0, help_text='بایت')),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_attachment',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
