# Generated by Django 5.2.15 on 2026-08-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/%Y/%m/'),
        ),
    ]
