# Generated by Django 5.2.15 on 2026-07-27 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='private', max_length=8)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_blog_post',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('starts_at', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('attendees', models.PositiveIntegerField(default=0)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mode', models.CharField(choices=[('in_person', 'حضوری'), ('online', 'آنلاین')], default='in_person', max_length=10)),
                ('join_link', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='private', max_length=8)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_event',
                'ordering': ['starts_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('doc_type', models.CharField(choices=[('contract', 'قرارداد'), ('training', 'آموزشی'), ('minutes', 'صورت\u200cجلسه'), ('report', 'گزارش')], default='report', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='knowledge/')),
                ('size', models.CharField(blank=True, max_length=32)),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='private', max_length=8)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_docs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_knowledge_doc',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('photo', 'تصویر'), ('video', 'ویدیو')], default='photo', max_length=6)),
                ('title', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('color', models.CharField(default='#1f4f99', max_length=9)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='private', max_length=8)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_media_item',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='private', max_length=8)),
                ('scope', models.CharField(choices=[('global', 'سراسری'), ('holding', 'هلدینگ'), ('company', 'شرکت')], default='global', max_length=8)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.company')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.holding')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'news',
                'db_table': 'content_news',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['tenant', 'pinned', '-created_at'], name='content_new_tenant__a0eb89_idx')],
            },
        ),
    ]
