# Generated by Django 5.2.15 on 2026-08-04 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerTechnologist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('expertise', models.CharField(blank=True, max_length=200)),
                ('projects', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_partner_technologist',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('magazine', models.CharField(choices=[('bonyad', 'ماهنامه بنیاد'), ('bonyadtech', 'نشریه بنیادتک')], default='bonyad', max_length=12)),
                ('issue_no', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=300)),
                ('season', models.CharField(blank=True, max_length=60)),
                ('stage', models.CharField(choices=[('collect', 'گردآوری محتوا'), ('edit', 'ویراستاری'), ('layout', 'صفحه\u200cآرایی'), ('print', 'چاپ و توزیع'), ('published', 'منتشر شده')], default='collect', max_length=10)),
                ('articles', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_publication_issue',
                'ordering': ['-issue_no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RndDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=200)),
                ('holding', models.CharField(blank=True, max_length=200)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='۰ تا ۱۰۰ روی ماشین وضعیت تدوین')),
                ('status_label', models.CharField(blank=True, max_length=200)),
                ('obstacles', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_rnd_doc',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportedProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('trl', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_supported_product',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportedVenture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('support_type', models.CharField(choices=[('tech_contract', 'قرارداد فناورانه'), ('seed', 'بذرمایه'), ('vc', 'سرمایه خطرپذیر')], default='seed', max_length=16)),
                ('field', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_supported_venture',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
