# Generated by Django 5.2.15 on 2026-08-04 12:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_partnertechnologist_publicationissue_rnddoc_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('news', 'خبر'), ('blog', 'بلاگ'), ('event', 'رویداد'), ('media', 'رسانه'), ('doc', 'سند'), ('forum', 'تالار')], max_length=8)),
                ('object_id', models.UUIDField()),
                ('body', models.TextField()),
                ('accepted', models.BooleanField(default=False, help_text='پاسخ برگزیده')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'content_comment',
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['kind', 'object_id'], name='content_com_kind_46aea7_idx')],
            },
        ),
    ]
