# Generated by Django 5.2.15 on 2026-08-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_contentcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.CharField(blank=True, help_text='نام تصویر در public/img یا URL', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, help_text='نام تصویر در public/img یا URL', max_length=120),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='image',
            field=models.CharField(blank=True, help_text='نام تصویر در public/img یا URL', max_length=120),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.CharField(blank=True, help_text='نام تصویر در public/img یا URL', max_length=120),
        ),
    ]
