# Generated by Django 5.2.15 on 2026-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_blogpost_image_event_image_mediaitem_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='ظرفیت کل ثبت\u200cنام؛ ۰ یعنی نامحدود'),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('meeting', 'جلسه'), ('workshop', 'کارگاه'), ('webinar', 'وبینار'), ('conference', 'همایش'), ('training', 'آموزش')], max_length=12),
        ),
    ]
