# Generated by Django 5.2.15 on 2026-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_event_capacity_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='duration',
            field=models.CharField(blank=True, help_text='مدت ویدیو، مثل ۰۴:۳۲', max_length=8),
        ),
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.CharField(blank=True, choices=[('economic', 'اقتصادی'), ('social', 'اجتماعی'), ('cultural', 'فرهنگی'), ('civil', 'عمرانی'), ('org', 'سازمانی')], help_text='برچسب موضوعی خبر', max_length=10),
        ),
    ]
