# Generated by Django 5.2.15 on 2026-07-27 20:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(blank=True, help_text='کلید یکتا برای نقش\u200cهای سیستمی', max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('platform', 'پلتفرم'), ('tenant', 'سازمان'), ('group', 'گروه')], default='tenant', max_length=12)),
                ('permissions', models.JSONField(default=list, help_text='فهرست شناسه\u200cهای مجوز')),
                ('is_system', models.BooleanField(default=False, help_text='نقش پیش\u200cفرض غیرقابل\u200cحذف')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'rbac_role',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.company')),
                ('holding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenancy.holding')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rbac.role')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rbac_role_assignment',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'title'), name='uniq_role_title_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='roleassignment',
            constraint=models.UniqueConstraint(fields=('user', 'role', 'tenant'), name='uniq_user_role_tenant'),
        ),
    ]
