# Generated by Django 5.2.15 on 2026-08-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='org',
            field=models.CharField(blank=True, help_text='سازمان/شرکت نمایشی', max_length=200),
        ),
    ]
