# Generated by Django 5.2.15 on 2026-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionentry',
            name='attachment',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
