# Generated by Django 5.2.15 on 2026-08-04 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messagereaction'),
        ('social', '0004_group_invite_code_group_slow_mode_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='social.group'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.JSONField(blank=True, help_text='{kind,name,size,url}', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=False, help_text='حذف نرم — «این پیام حذف شد»'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='mentions',
            field=models.JSONField(blank=True, default=list, help_text='شناسهٔ کاربران منشن\u200cشده'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
