# Generated by Django 5.2.15 on 2026-08-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_channel_group_message_attachment_message_deleted_and_more'),
        ('social', '0005_group_topics_enabled_grouptopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='تاپیک گروه؛ خالی = فید اصلی', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.grouptopic'),
        ),
    ]
