# Generated by Django 5.2.15 on 2026-08-08 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_directmessage_attachment_alter_directmessage_text_and_more'),
        ('tenancy', '0003_tenant_short_name_tenant_sso_allow_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.company'),
        ),
        migrations.AddField(
            model_name='channel',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenancy.holding'),
        ),
        migrations.AddField(
            model_name='channel',
            name='scope',
            field=models.CharField(choices=[('global', 'سراسری'), ('holding', 'هلدینگ'), ('company', 'شرکت')], default='global', max_length=8),
        ),
    ]
