# Generated by Django 5.2.15 on 2026-07-27 21:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='کد طرح، مثل NF-1405-0001', max_length=32)),
                ('title_fa', models.CharField(max_length=300)),
                ('title_en', models.CharField(blank=True, max_length=300)),
                ('field', models.CharField(blank=True, max_length=200)),
                ('macro_field', models.CharField(blank=True, max_length=200)),
                ('rahbar', models.CharField(blank=True, help_text='شرکت شتابدهنده/راهبر', max_length=200)),
                ('nazer', models.CharField(blank=True, help_text='ناظر', max_length=200)),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('share_percent', models.PositiveSmallIntegerField(default=0, help_text='سهم صندوق (٪)')),
                ('duration_months', models.PositiveSmallIntegerField(default=0)),
                ('contract_no', models.CharField(blank=True, max_length=64)),
                ('stage', models.CharField(choices=[('proposal', 'دریافت پروپوزال'), ('screening', 'ارزیابی اولیه'), ('jury', 'ارزیابی موشکافانه'), ('approval', 'تصویب طرح'), ('contract', 'تنظیم قرارداد'), ('monitoring', 'نظارت و راهبری'), ('exit', 'خروج از صندوق')], default='proposal', max_length=12)),
                ('sub_status', models.CharField(blank=True, max_length=200)),
                ('green_path', models.BooleanField(default=False, help_text='مسیر سبز/تسریع')),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('screening_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jury_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200)),
                ('team_type', models.CharField(blank=True, max_length=60)),
                ('team_city', models.CharField(blank=True, max_length=120)),
                ('fund_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_nf', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_nf_project',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_type', models.CharField(default='stage', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('await_order', 'در انتظار دستور پرداخت'), ('ordered', 'دستور پرداخت صادر شد'), ('paid', 'پرداخت انجام شد'), ('docs_to_fund', 'اسناد تحویل صندوق شد'), ('docs_to_team', 'اسناد به تیم مجری ارسال شد')], default='await_order', max_length=16)),
                ('doc_no', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fund.nfproject')),
            ],
            options={
                'db_table': 'fund_nf_payment',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfGuarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='fund.nfproject')),
            ],
            options={
                'db_table': 'fund_nf_guarantee',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(default='stage', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('due', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_upload', 'در انتظار بارگذاری'), ('under_review', 'در حال بررسی'), ('needs_fix', 'نیازمند اصلاح'), ('approved', 'تایید نهایی')], default='pending_upload', max_length=16)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fund.nfproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_nf_report',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfReportChainStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('late', models.BooleanField(default=False, help_text='تشدید ۱۵ روزه')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chain', to='fund.nfreport')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_nf_report_chain',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(max_length=60)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='fund.nfproject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_nf_request',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='nfproject',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_nf_code_per_tenant'),
        ),
    ]
