# Generated by Django 5.2.15 on 2026-08-02 14:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('applicant', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('registered', 'ثبت\u200cشده'), ('screening', 'انتخاب اولیه'), ('judging', 'داوری'), ('allocated', 'تخصیص\u200cیافته'), ('monitoring', 'در حال پایش')], default='registered', max_length=12)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('roi', models.CharField(blank=True, max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_simple_fund',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
