# Generated by Django 5.2.15 on 2026-08-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfproject',
            name='finance',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nfproject',
            name='gantt',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nfproject',
            name='mother_project',
            field=models.CharField(blank=True, help_text='پروژه مادر (رویداد/فراخوان)', max_length=300),
        ),
        migrations.AddField(
            model_name='nfproject',
            name='team_manager',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='nfproject',
            name='team_members',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nfproject',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
