# Generated by Django 5.2.15 on 2026-08-04 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_nfproject_finance_nfproject_gantt_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='approved',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fund',
            name='committee',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fund',
            name='field',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fund',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='fund',
            name='requested',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='fund',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FundKpi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.CharField(blank=True, max_length=80)),
                ('target', models.CharField(blank=True, max_length=80)),
                ('on_track', models.BooleanField(default=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='fund.fund')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_kpi',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTranche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.CharField(blank=True, max_length=80)),
                ('condition', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('pending', 'در انتظار'), ('conditional', 'مشروط')], default='pending', max_length=12)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tranches', to='fund.fund')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_tranche',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('items', models.PositiveSmallIntegerField(default=0)),
                ('committee', models.CharField(blank=True, max_length=200)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_review_session',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
