# Generated by Django 5.2.15 on 2026-08-04 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_fund_approved_fund_committee_fund_field_fund_notes_and_more'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('focus', models.CharField(blank=True, max_length=300)),
                ('trl_range', models.CharField(blank=True, max_length=40)),
                ('manager', models.CharField(blank=True, max_length=200)),
                ('active_projects', models.PositiveSmallIntegerField(default=0)),
                ('capital', models.CharField(blank=True, max_length=80)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_entity',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeedInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.CharField(max_length=200)),
                ('field', models.CharField(blank=True, max_length=120)),
                ('stage', models.CharField(choices=[('screening', 'غربالگری'), ('evaluation', 'ارزیابی'), ('due_diligence', 'ارزیابی موشکافانه'), ('contract', 'قرارداد'), ('monitoring', 'نظارت و راهبری'), ('exit', 'خروج')], default='screening', max_length=14)),
                ('requested', models.CharField(blank=True, max_length=80)),
                ('approved', models.CharField(blank=True, max_length=80)),
                ('equity_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valuation', models.CharField(blank=True, max_length=80)),
                ('kpi_status', models.CharField(blank=True, max_length=300)),
                ('exit_plan', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'fund_seed_investment',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
