# Generated by Django 5.2.15 on 2026-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_fundentity_seedinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfproject',
            name='jury_dimensions',
            field=models.JSONField(blank=True, default=list, help_text='[{title,max,score}] ابعاد داوری'),
        ),
        migrations.AddField(
            model_name='nfproject',
            name='screening_scores',
            field=models.JSONField(blank=True, default=list, help_text='امتیاز هر معیار غربالگری'),
        ),
    ]
