// Central route registry — no hard-coded paths elsewhere.
export const routes = {
  login: "/login",
  dashboard: "/dashboard",
  groups: "/groups",
  forum: "/forum",
  news: "/news",
  blog: "/blog",
  events: "/events",
  media: "/media",
  knowledge: "/knowledge",
  projects: "/projects",
  contracts: "/contracts",
  funds: "/funds",
  training: "/training",
  polls: "/polls",
  tickets: "/tickets",
  research: "/research",
  awards: "/awards",
  notifications: "/notifications",
  chat: "/chat",
  reports: "/reports",
  admin: "/admin",
  users: "/admin/users",
  roles: "/admin/roles",
} as const;
