# Generated by Django 5.2.15 on 2026-07-27 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('stage', models.CharField(choices=[('negotiation', 'مذاکره'), ('rfp', 'فراخوان'), ('evaluation', 'داوری'), ('executing', 'در حال اجرا'), ('settled', 'تسویه\u200cشده')], default='negotiation', max_length=12)),
                ('contract_type', models.CharField(choices=[('tech', 'فناورانه'), ('research', 'پژوهشی'), ('construction', 'عمرانی'), ('service', 'خدماتی')], default='service', max_length=14)),
                ('method', models.CharField(choices=[('public_call', 'فراخوان عمومی'), ('limited', 'استعلام محدود'), ('no_tender', 'ترک تشریفات')], default='public_call', max_length=12)),
                ('value', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('guarantee', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_contract',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('approved', 'تأیید شده'), ('pending', 'در انتظار'), ('rejected', 'رد شده')], default='pending', max_length=8)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_approval',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'پرداخت\u200cشده'), ('pending', 'در انتظار تأیید'), ('future', 'آینده')], default='future', max_length=8)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.contract')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_payment',
                'ordering': ['due'],
                'abstract': False,
            },
        ),
    ]
