# Generated by Django 5.2.15 on 2026-08-02 20:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESignDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=400)),
                ('kind', models.CharField(choices=[('nf', 'قرارداد صندوق نوآور'), ('tech', 'قرارداد تبادل فناوری'), ('amendment', 'متمم قرارداد'), ('minutes', 'صورت\u200cجلسه')], default='nf', max_length=12)),
                ('related_to', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(default='امضای الکترونیک غیرحضوری', max_length=60)),
                ('letter_no', models.CharField(blank=True, help_text='شماره نامه پس از تکمیل امضاها', max_length=64)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_esign_doc',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ESignStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=120)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('signed', 'امضا شد'), ('awaiting', 'در انتظار امضا'), ('queued', 'در نوبت')], default='queued', max_length=10)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='contracts.esigndocument')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_esign_step',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechTransferContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(default='تبادل فناوری', help_text='نوع قرارداد', max_length=60)),
                ('title', models.CharField(max_length=300)),
                ('nazer', models.CharField(blank=True, help_text='ناظر فنی پروژه', max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('holding', models.CharField(blank=True, help_text='هلدینگ متقاضی', max_length=200)),
                ('company', models.CharField(blank=True, help_text='شرکت متقاضی', max_length=200)),
                ('mojri', models.CharField(blank=True, help_text='مجری پروژه', max_length=200)),
                ('company_role', models.CharField(blank=True, max_length=120)),
                ('daneshmand_role', models.CharField(blank=True, max_length=120)),
                ('amount', models.CharField(blank=True, help_text='مبلغ قرارداد (نمایشی)', max_length=80)),
                ('commitment', models.CharField(blank=True, help_text='تعهد بنیاد (نمایشی)', max_length=80)),
                ('physical_progress', models.PositiveSmallIntegerField(default=0)),
                ('time_progress', models.PositiveSmallIntegerField(default=0)),
                ('financial_progress', models.PositiveSmallIntegerField(default=0)),
                ('guarantee', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_tech_transfer',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('method', models.CharField(choices=[('public', 'مناقصه عمومی'), ('limited', 'مناقصه محدود'), ('auction', 'مزایده'), ('no_formality', 'ترک تشریفات')], default='public', max_length=14)),
                ('stage', models.CharField(choices=[('publish', 'انتشار آگهی'), ('receive', 'دریافت پاکات'), ('commission', 'کمیسیون معاملات'), ('award', 'ابلاغ برنده'), ('contract', 'عقد قرارداد')], default='publish', max_length=12)),
                ('participants', models.PositiveSmallIntegerField(default=0)),
                ('session_date', models.CharField(blank=True, help_text='تاریخ جلسه (جلالی نمایشی)', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'contracts_tender',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
